name: Gemini File Modifier

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file to modify (e.g., src/data.json)'
        required: true
        default: 'README.md'
      modification_prompt:
        description: 'The instruction for Gemini (e.g., "Summarize this file into five bullet points.")'
        required: true
        default: 'Explain this file in two sentences.'

jobs:
  modify_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for committing changes
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          
      # Step 2: Read the file content and set as environment variable
      - name: Read File Content
        id: file_content
        run: |
          FILE_CONTENT=$(cat ${{ github.event.inputs.file_path }} | sed 's/\"/\\\"/g')
          echo "file_content<<EOF" >> $GITHUB_ENV
          echo "$FILE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      # Step 3: Construct the Full Prompt
      - name: Construct Prompt
        id: full_prompt
        run: |
          FULL_PROMPT="${{ github.event.inputs.modification_prompt }}\n\nFile Content to Modify:\n\`\`\`\n${{ env.file_content }}\n\`\`\`\n\n- ONLY output the complete modified content for the file. DO NOT include any introductory or explanatory text or markdown fences."
          echo "full_prompt<<EOF" >> $GITHUB_ENV
          echo "$FULL_PROMPT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Step 4: Install Gemini CLI (REQUIRED STEP!)
      - name: Install Gemini CLI
        uses: google-github-actions/run-gemini-cli@main

      # Step 5: Call Gemini and Write to File (Using inline auth)
      - name: Generate New Content and Write to File
        id: generate_and_write
        run: |
          PROMPT_FILE="gemini_prompt.txt"
          OUTPUT_FILE="${{ github.event.inputs.file_path }}"

          # 1. Write the full prompt to a temporary file
          echo "${{ env.full_prompt }}" > $PROMPT_FILE
          
          echo "Sending prompt to Gemini..."
          
          # 2. Execute the gemini CLI using inline assignment for guaranteed authentication
          NEW_CONTENT=$(GEMINI_API_KEY="${{ secrets.GEMINI_HTML_API_KEY }}" cat $PROMPT_FILE | gemini)
          
          # 3. Basic Error Check
          if [[ -z "$NEW_CONTENT" ]]; then
              echo "Gemini API returned empty content or an error occurred."
              echo "::error::Gemini API Call Failed or returned empty content. Check previous step logs for potential API errors."
              exit 1
          fi
          
          # 4. Write the new content to the original file
          echo "Writing new content to $OUTPUT_FILE"
          echo "$NEW_CONTENT" > $OUTPUT_FILE
          
      # Step 6: Commit the changes
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Gemini Auto-Update: ${{ github.event.inputs.file_path }} modified'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}