name: Gemini File Modifier

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file to modify (e.g., src/data.json)'
        required: true
        default: 'README.md'
      modification_prompt:
        description: 'The instruction for Gemini (e.g., "Summarize this file into five bullet points.")'
        required: true
        default: 'Explain this file in two sentences.'

jobs:
  modify_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for committing changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Read File Content
        id: file_content
        run: |
          FILE_CONTENT=$(cat ${{ github.event.inputs.file_path }} | sed 's/\"/\\\"/g')
          echo "file_content<<EOF" >> $GITHUB_ENV
          echo "$FILE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Construct Prompt
        id: full_prompt
        run: |
          FULL_PROMPT="${{ github.event.inputs.modification_prompt }}\n\nFile Content to Modify:\n\`\`\`\n${{ env.file_content }}\n\`\`\`\n\n- ONLY output the complete modified content for the file. DO NOT include any introductory or explanatory text or markdown fences."
          echo "full_prompt<<EOF" >> $GITHUB_ENV
          echo "$FULL_PROMPT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # --- START OF MODIFIED SECTION ---

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3 version

      - name: Install Google Generative AI Library
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Generate New Content with Gemini (Python Script)
        id: gemini_generation
        run: |
          # Use a Python script to call Gemini and capture its output
          # The output will be stored in the GITHUB_ENV variable 'GEMINI_CONTENT'
          python_script_output=$(python -c "
import google.generativeai as genai
import os
import sys

# Configure Gemini with the API key
genai.configure(api_key=os.environ.get('GEMINI_API_KEY'))

# Choose the model (gemini-pro is a common choice for text generation)
model = genai.GenerativeModel('gemini-pro')

# Get the prompt from the environment variable
prompt = os.environ.get('FULL_PROMPT')

try:
    # Generate content
    response = model.generate_content(prompt)
    
    # Check if a response was received and has text content
    if response and response.text:
        print(response.text)
    else:
        # If no text content, print an error to stderr and exit with a non-zero code
        print('Error: Gemini returned no text content.', file=sys.stderr)
        sys.exit(1)
except Exception as e:
    # Catch any exceptions during the API call
    print(f'Error calling Gemini API: {e}', file=sys.stderr)
    sys.exit(1)
          "
          )
          # Store the output of the Python script into a multiline environment variable
          echo "GEMINI_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$python_script_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_HTML_API_KEY }}
          FULL_PROMPT: ${{ env.full_prompt }}

      - name: Write Modified Content
        id: write_content
        run: |
          # Retrieve the content generated by the Python script from the environment variable
          NEW_CONTENT="${{ env.GEMINI_CONTENT }}"
          OUTPUT_FILE="${{ github.event.inputs.file_path }}"

          echo "DEBUG: Captured Content Length: ${#NEW_CONTENT}"

          # Check if the output is empty (after potential errors from the Python script)
          if [[ -z "$NEW_CONTENT" ]]; then
              echo "Gemini returned empty content. Stopping to prevent file erasure."
              echo "::error::Gemini model returned empty content. Check the prompt, API status, or the Python script's output in the logs above."
              exit 1
          fi
          
          # Write the new content to the original file
          echo "$NEW_CONTENT" | tee "$OUTPUT_FILE"
          
      # --- END OF MODIFIED SECTION ---

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Gemini Auto-Update: ${{ github.event.inputs.file_path }} modified'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}